sphere0
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (-0.500000 -0.500000 -0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere1
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (-0.500000 0.500000 -0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere2
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (-0.500000 0.500000 0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere3
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (-0.500000 -0.500000 0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere4
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (-0.500000 0.000000 0.000000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere5
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.000000 -0.500000 0.000000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere6
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.000000 0.500000 0.000000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere7
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.000000 0.000000 -0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere8
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.000000 0.000000 0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere9
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.500000 -0.500000 -0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere10
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.500000 0.500000 -0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere11
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.500000 0.500000 0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere12
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.500000 -0.500000 0.500000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

sphere13
{
    surface sphere;
    scale (0.181392 0.181392 0.181392);
    transform
    {
         coordinateSystem
         {
             type cartesian;
             origin (0.500000 0.000000 0.000000);
             coordinateRotation
             {
                 type axesRotation;
                 e1 (1 0 0);
                 e2 (0 0 1);
             }
         }
    }
}

